import {
  ArrowUpRight,
  BarChart3,
  Boxes,
  CreditCard,
  ReceiptText,
  TrendingUp,
} from "lucide-react";

import {
  getBusinessReportAction,
} from "@/lib/reports/actions";

export const dynamic = "force-dynamic";

export default async function ReportsPage() {
  const report =
    await getBusinessReportAction();

  return (
    <div className="mx-auto max-w-[1600px]">
      {/* Page header */}
      <div className="mb-8 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <div className="flex items-center gap-2 text-violet-600">
            <BarChart3 className="h-4 w-4" />

            <span className="text-[11px] font-bold uppercase tracking-[0.18em]">
              Business intelligence
            </span>
          </div>

          <h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">
            Reports & insights
          </h1>

          <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500 sm:text-base">
            Understand how your business is performing across
            revenue, purchases, expenses and inventory.
          </p>
        </div>

        <div className="flex items-center gap-2 rounded-2xl border border-violet-100 bg-white px-4 py-3 shadow-sm">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-50 text-violet-600">
            <TrendingUp className="h-5 w-5" />
          </div>

          <div>
            <p className="text-xs font-medium text-slate-400">
              Business overview
            </p>

            <p className="mt-0.5 text-sm font-semibold text-slate-900">
              Performance snapshot
            </p>
          </div>
        </div>
      </div>

      {/* Metrics */}
      <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">
        <ReportCard
          title="Revenue"
          value={report.sales.amount}
          description={`${report.sales.count} completed sales`}
          icon={
            <CreditCard className="h-5 w-5" />
          }
        />

        <ReportCard
          title="Purchases"
          value={report.purchases.amount}
          description={`${report.purchases.count} received purchases`}
          icon={
            <ReceiptText className="h-5 w-5" />
          }
        />

        <ReportCard
          title="Expenses"
          value={report.expenses.amount}
          description={`${report.expenses.count} expenses recorded`}
          icon={
            <ArrowUpRight className="h-5 w-5" />
          }
        />

        <ReportCard
          title="Profit estimate"
          value={report.profit}
          description="Revenue − purchases − expenses"
          icon={
            <TrendingUp className="h-5 w-5" />
          }
        />
      </section>

      {/* Analytics */}
      <section className="mt-8 grid gap-6 xl:grid-cols-[1.2fr_1fr]">
        {/* Sales */}
        <div className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm shadow-slate-200/40 sm:p-7">
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="flex items-center gap-2">
                <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-50 text-violet-600">
                  <TrendingUp className="h-4 w-4" />
                </div>

                <div>
                  <p className="text-sm font-bold text-slate-900">
                    Sales performance
                  </p>

                  <p className="mt-0.5 text-xs text-slate-400">
                    Revenue generated by completed sales
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-7 rounded-2xl border border-violet-100 bg-gradient-to-br from-violet-50 to-white p-6">
            <p className="text-sm font-medium text-slate-500">
              Total revenue
            </p>

            <p className="mt-3 text-4xl font-bold tracking-tight text-slate-950">
              {report.sales.amount.toLocaleString()}
            </p>

            <div className="mt-5 flex items-center gap-2 text-sm">
              <span className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-violet-700 shadow-sm">
                {report.sales.count.toLocaleString()} sales
              </span>

              <span className="text-xs text-slate-400">
                completed transactions
              </span>
            </div>
          </div>
        </div>

        {/* Inventory */}
        <div className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm shadow-slate-200/40 sm:p-7">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-amber-50 text-amber-600">
              <Boxes className="h-4 w-4" />
            </div>

            <div>
              <p className="text-sm font-bold text-slate-900">
                Inventory position
              </p>

              <p className="mt-0.5 text-xs text-slate-400">
                Current stock across your business
              </p>
            </div>
          </div>

          <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-1">
            <InventoryMetric
              label="Units in stock"
              value={report.inventory.units}
              description="Available inventory units"
            />

            <InventoryMetric
              label="Stock value"
              value={report.inventory.value}
              description="Current inventory valuation"
            />
          </div>
        </div>
      </section>

      {/* Summary */}
      <section className="mt-8 rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm shadow-slate-200/40 sm:p-7">
        <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-[11px] font-bold uppercase tracking-[0.16em] text-slate-400">
              Financial summary
            </p>

            <h2 className="mt-2 text-xl font-bold tracking-tight text-slate-950">
              Estimated business performance
            </h2>

            <p className="mt-2 text-sm text-slate-500">
              A consolidated view of your current operational data.
            </p>
          </div>

          <div className="rounded-2xl bg-slate-950 px-5 py-4 text-white">
            <p className="text-xs font-medium text-slate-400">
              Estimated profit
            </p>

            <p className="mt-1 text-2xl font-bold">
              {report.profit.toLocaleString()}
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}

function ReportCard({
  title,
  value,
  description,
  icon,
}: {
  title: string;
  value: number;
  description: string;
  icon: React.ReactNode;
}) {
  return (
    <div className="group relative overflow-hidden rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm shadow-slate-200/40 transition duration-200 hover:-translate-y-0.5 hover:shadow-md">
      <div className="absolute right-0 top-0 h-28 w-28 rounded-full bg-violet-50/70 blur-2xl" />

      <div className="relative">
        <div className="flex items-center justify-between gap-4">
          <p className="text-sm font-semibold text-slate-500">
            {title}
          </p>

          <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-50 text-violet-600 transition group-hover:bg-violet-50">
            {icon}
          </div>
        </div>

        <p className="mt-7 text-3xl font-bold tracking-tight text-slate-950">
          {value.toLocaleString()}
        </p>

        <p className="mt-2 text-xs leading-5 text-slate-400">
          {description}
        </p>
      </div>
    </div>
  );
}

function InventoryMetric({
  label,
  value,
  description,
}: {
  label: string;
  value: number;
  description: string;
}) {
  return (
    <div className="rounded-2xl border border-slate-100 bg-slate-50/70 p-5">
      <p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">
        {label}
      </p>

      <p className="mt-3 text-2xl font-bold tracking-tight text-slate-950">
        {value.toLocaleString()}
      </p>

      <p className="mt-2 text-xs text-slate-400">
        {description}
      </p>
    </div>
  );
}