import {
BarChart3,
Boxes,
CreditCard,
ReceiptText,
TrendingUp,
} from "lucide-react";

import {
getBusinessReportAction,
} from "@/lib/reports/actions";

export const dynamic = "force-dynamic";

export default async function ReportsPage() {
const report =
await getBusinessReportAction();

return ( <div className="space-y-6">
{/* Reports hero */} <section className="relative overflow-hidden rounded-[1.75rem] bg-gradient-to-r from-slate-950 via-slate-950 to-cyan-950 px-6 py-7 text-white shadow-xl shadow-slate-950/10 sm:px-8 sm:py-8"> <div className="pointer-events-none absolute inset-0"> <div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-cyan-400/10 blur-3xl" /> <div className="absolute bottom-0 left-1/3 h-40 w-80 rounded-full bg-violet-500/10 blur-3xl" /> </div>


    <div className="relative flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
      <div>
        <div className="flex flex-wrap items-center gap-2">
          <span className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.18em] text-slate-300">
            Reports
          </span>

          <span className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-medium text-slate-300">
            Business overview
          </span>
        </div>

        <h1 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">
          Reports & insights
        </h1>

        <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">
          Understand how your business is performing across
          revenue, purchases, expenses and inventory.
        </p>
      </div>

      <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-white/10 text-white">
        <BarChart3 className="h-6 w-6" />
      </div>
    </div>
  </section>

  {/* Business performance overview */}
  <section>
    <div className="mb-4">
      <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">
        Business performance
      </p>

      <h2 className="mt-1 text-xl font-semibold tracking-tight text-slate-900">
        Performance overview
      </h2>

      <p className="mt-2 text-sm text-slate-500">
        A consolidated view of revenue, purchasing,
        expenses and estimated profitability.
      </p>
    </div>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <ReportCard
        label="Revenue"
        value={report.sales.amount}
        description={`${report.sales.count} completed sales`}
        icon={
          <TrendingUp className="h-5 w-5" />
        }
        borderTone="border-emerald-200"
        iconTone="text-emerald-700"
        valueTone="text-emerald-900"
      />

      <ReportCard
        label="Purchases"
        value={report.purchases.amount}
        description={`${report.purchases.count} received purchases`}
        icon={
          <ReceiptText className="h-5 w-5" />
        }
        borderTone="border-blue-200"
        iconTone="text-blue-700"
        valueTone="text-blue-900"
      />

      <ReportCard
        label="Expenses"
        value={report.expenses.amount}
        description={`${report.expenses.count} expenses recorded`}
        icon={
          <CreditCard className="h-5 w-5" />
        }
        borderTone="border-amber-200"
        iconTone="text-amber-700"
        valueTone="text-amber-900"
      />

      <ReportCard
        label="Profit estimate"
        value={report.profit}
        description="Revenue minus purchases and expenses"
        icon={
          <BarChart3 className="h-5 w-5" />
        }
        borderTone="border-violet-200"
        iconTone="text-violet-700"
        valueTone="text-violet-900"
      />
    </div>
  </section>

  {/* Operational performance */}
  <section className="grid gap-6 lg:grid-cols-2">
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="border-b border-slate-100 px-5 py-5 sm:px-6 sm:py-6">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-50 text-emerald-700">
            <TrendingUp className="h-5 w-5" />
          </div>

          <div>
            <p className="text-[10px] font-bold uppercase tracking-[0.15em] text-slate-400">
              Sales performance
            </p>

            <h2 className="mt-1 font-semibold tracking-tight text-slate-900">
              Revenue performance
            </h2>

            <p className="mt-1 text-sm text-slate-500">
              Revenue generated by completed sales.
            </p>
          </div>
        </div>
      </div>

      <div className="p-5 sm:p-6">
        <div className="rounded-xl border border-slate-100 bg-slate-50/70 p-6">
          <p className="text-[10px] font-bold uppercase tracking-[0.15em] text-slate-400">
            Total revenue
          </p>

          <p className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">
            {report.sales.amount.toLocaleString()}
          </p>

          <p className="mt-2 text-xs text-slate-500">
            {report.sales.count.toLocaleString()} completed sales
          </p>
        </div>
      </div>
    </div>

    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="border-b border-slate-100 px-5 py-5 sm:px-6 sm:py-6">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-50 text-violet-700">
            <Boxes className="h-5 w-5" />
          </div>

          <div>
            <p className="text-[10px] font-bold uppercase tracking-[0.15em] text-slate-400">
              Inventory
            </p>

            <h2 className="mt-1 font-semibold tracking-tight text-slate-900">
              Inventory position
            </h2>

            <p className="mt-1 text-sm text-slate-500">
              Current stock across your business.
            </p>
          </div>
        </div>
      </div>

      <div className="grid gap-4 p-5 sm:grid-cols-2 sm:p-6">
        <div className="rounded-xl border border-slate-100 bg-slate-50/70 p-5">
          <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">
            Units
          </p>

          <p className="mt-3 text-2xl font-semibold tracking-tight text-slate-950">
            {report.inventory.units.toLocaleString()}
          </p>

          <p className="mt-2 text-xs text-slate-500">
            Available inventory units
          </p>
        </div>

        <div className="rounded-xl border border-slate-100 bg-slate-50/70 p-5">
          <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">
            Stock value
          </p>

          <p className="mt-3 text-2xl font-semibold tracking-tight text-slate-950">
            {report.inventory.value.toLocaleString()}
          </p>

          <p className="mt-2 text-xs text-slate-500">
            Current inventory valuation
          </p>
        </div>
      </div>
    </div>
  </section>

  {/* Financial summary */}
  <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    <div className="flex flex-col gap-5 border-b border-slate-100 px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6 sm:py-6">
      <div>
        <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">
          Financial summary
        </p>

        <h2 className="mt-1 text-lg font-semibold tracking-tight text-slate-950">
          Estimated business performance
        </h2>

        <p className="mt-2 text-sm text-slate-500">
          A consolidated view of your current operational data.
        </p>
      </div>

      <div className="rounded-2xl bg-slate-950 px-5 py-4 text-white">
        <p className="text-xs text-slate-400">
          Estimated profit
        </p>

        <p className="mt-1 text-2xl font-semibold">
          {report.profit.toLocaleString()}
        </p>
      </div>
    </div>

    <div className="grid gap-4 p-5 sm:grid-cols-3 sm:p-6">
      <SummaryItem
        label="Revenue"
        value={report.sales.amount}
      />

      <SummaryItem
        label="Purchases"
        value={report.purchases.amount}
      />

      <SummaryItem
        label="Expenses"
        value={report.expenses.amount}
      />
    </div>
  </section>
</div>


);
}

function ReportCard({
label,
value,
description,
icon,
borderTone = "border-slate-200",
iconTone = "text-violet-700",
valueTone = "text-slate-950",
}: {
label: string;
value: number;
description: string;
icon: React.ReactNode;
borderTone?: string;
iconTone?: string;
valueTone?: string;
}) {
return (
<div
className={[
"rounded-2xl border bg-white p-5 shadow-sm transition hover:shadow-md",
borderTone,
].join(" ")}
> <div className="flex items-start justify-between gap-4"> <div> <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">
{label} </p>


      <p
        className={[
          "mt-3 text-3xl font-semibold tracking-tight",
          valueTone,
        ].join(" ")}
      >
        {value.toLocaleString()}
      </p>
    </div>

    <div
      className={[
        "flex h-10 w-10 items-center justify-center rounded-xl bg-slate-50",
        iconTone,
      ].join(" ")}
    >
      {icon}
    </div>
  </div>

  <p className="mt-4 text-xs leading-5 text-slate-500">
    {description}
  </p>
</div>


);
}

function SummaryItem({
label,
value,
}: {
label: string;
value: number;
}) {
return ( <div className="rounded-xl border border-slate-100 bg-slate-50/70 p-5"> <p className="text-[10px] font-bold uppercase tracking-[0.14em] text-slate-400">
{label} </p>


  <p className="mt-3 text-xl font-semibold tracking-tight text-slate-950">
    {value.toLocaleString()}
  </p>
</div>


);
}
